### ISSUE TITLE
Lab 02 issue

### ISSUE THREAD

**Issue by jacobtnyoung** [jacobtnyoung/SAND#20]
Hi @cjstewa9 and @lecy. Will you try running this command:

```
url <- "https://github.com/jacobtnyoung/SAND/blob/main/data/lab_data/lab-02-undirected-example.csv"

mat.u <- read.csv( url )

View( mat.u )

```
Tell me whether you get a matrix or some funky .html output. Mine looks like this:

<img width="1440" alt="Screenshot 2022-11-12 at 12 35 07 PM" src="https://user-images.githubusercontent.com/39632608/201491518-6deff7d1-3abd-4b88-ab88-0657ff62e8b4.png">

**Comment by cjstewa9** [comment]
Hi @jacobtnyoung. I got the same output as you.

**Comment by lecy** [comment]
You need the raw link. 

You are seeing the XML data from the landing page for the dataset otherwise. 

https://github.com/jacobtnyoung/SAND/blob/main/data/lab_data/lab-02-undirected-example.csv

vs

https://raw.githubusercontent.com/jacobtnyoung/SAND/main/data/lab_data/lab-02-undirected-example.csv

**Comment by jacobtnyoung** [comment]
Thanks @lecy!
